# Generated by Django 5.0.1 on 2024-02-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Содержимое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('count_views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
